### ISSUE TITLE
Instagram reset account

### ISSUE THREAD

**Issue by woj-ciech** [Frint0/email-enum#11]
Hey, It's really cool handy script but I've noticed that you actually reset password for given email which may raise some red flags.
I would recommend you to try to login or register for that email. Person won't get any notification or sign that he was checked.
Something like:

```python
driver.get("https://www.instagram.com/accounts/login/")
sleep(1.5)
driver.find_element_by_name('username').send_keys(email)
driver.find_element_by_name('password').send_keys("password")
#user.send_keys(Keys.RETURN)
# driver.find_element_by_tag_name("button").click()
sleep(2)
if "The username you entered doesn't belong to an account." in driver.page_source:
    result = "Not found"
elif "Sorry, your password was incorrect." in driver.page_source:
    result = "Found"
```
I cannot test it but I hope you get the idea.

**Comment by kotanrn** [comment]
I like where you’re going with this. You could probably do it in python on bash with just a few lines. 

—n0beard

**Comment by Akarshghale9** [comment]
Lol, that makes sense. I can now also think how you can use this program unethically :D. I mean just think If you try to validate the existence of email on different sites through the 'reset password' mechanism. It will literally spam the user of that associated email in their Inbox with multiple reset password emails. :laughing: This will creep the hell out of that person :laughing: . Perhaps that person might think he is under attack by some group or is being monitored.

**Comment by Akarshghale9** [comment]
Anyway, I have created a pull request that solves the problem.
