### ISSUE TITLE
geckodriver permissions 

### ISSUE THREAD

**Issue by waymbers** [Frint0/email-enum#12]
While running ./setup.sh as a regular user (as you cannot, and shouldnt typically, run as root) and after showing my requirements are satisfied, I recieve the two following errors involving the geckodriver ----------------------------------------------------------------------------------------------
"
chmod: changing permissions of 'geckodriver': Operation not permitted
mv: cannot move 'geckodriver' to '/home/lenovo/.local/bin/geckodriver': Permission denied

"
-----------------------------------------------------------------------------------------
running parrotOS kde

**Comment by Akarshghale9** [comment]
Your issue is under review.

**Comment by Frint0** [comment]
Make sure geckodriver is executable.
