### ISSUE TITLE
"Unable to locate element" on line 164 in sites.py

### ISSUE THREAD

**Issue by Akarshghale9** [Frint0/email-enum#13]
The problem seems to be in the **twitchCheck** function.

`driver.find_element_by_xpath("/html/body/div[1]/div/div[2]/nav/div/div[5]/div/div[1]/button").click()`

Looks like the code needs to be updated from the source code of the twitch site.

**Comment by yevgen2020** [comment]
Change to
`driver.find_element_by_xpath("//button[@data-a-target='login-button']").click()`
and Tweatch will be work

**Comment by Akarshghale9** [comment]
You may create a merge request @yevgen2020.
