### ISSUE TITLE
Suggestion: Username Enumeration Integration and Name Change

### ISSUE THREAD

**Issue by Akarshghale9** [Frint0/email-enum#15]
Hi, so I have seen in your To do's that you are looking to add '_**Username Enumeration**_'. I would like to suggest that there already is a project named '[**_Sherlock_**](https://github.com/sherlock-project/sherlock)' that checks for usernames in many popular sites. Might I suggest using their code to integrate and offer this mechanism in this program?

I would also like to suggest to change the name to something else as 'Email-Enum' just doesn't sound right. Well that's just my opinion.

**Comment by Frint0** [comment]
Email-Enum stands for email enumeration. Regarding the username enumeration feature, just use Sherlock itself. Adding it to my project is redundant.
