### ISSUE TITLE
Suggestion: Changing of program architecture to Requests

### ISSUE THREAD

**Issue by Akarshghale9** [Frint0/email-enum#16]
Hello, 
I would like to suggest changing the program architecture to using requests module instead of Selenium. To support my suggestion I have listed out some benefits.

- 1. Using requests instead of Selenium will drastically reduce the execution speed
- 2. This will decrease the number of dependencies as there's no longer any need of Firefox and selenium.
- 3. Provides a seamless experience. Selenium takes huge amount of time depending on the site as it's basically automating browsing. Requests directly handles through requests to the server instead of using a browser client.
- 4. Selenium is built for testing. Requests is built for gathering information hence, making it compatible to be used for this purpose.
- 5. Selenium increases the memory of the program as the number of sites to search are increased. Requests on the other hand, does not  affect the memory.

But this would mean a total refactoring of the code to be built on Requests architecture which is very time-consuming. But overall, I feel this will increase the efficiency and speed.

**Comment by Frint0** [comment]
Wouldn't be possible with requests due to sites being heavily dynamic and obfuscated source code.

**Comment by Akarshghale9** [comment]
is it not possible using web scraping? Beautiful soup?
