### ISSUE TITLE
pyfiglet not found/installed

### ISSUE THREAD

**Issue by acbekoac** [Frint0/email-enum#2]
running ./setup.sh on kali does not solve dependecy for _pyfiglet_, needed to install with _pip3 install pyfiglet_

**Comment by ionrover2** [comment]
I addressed this and containerized this in my pull request https://github.com/Frint0/email-enum/pull/1

**Comment by spmedia** [comment]
in your setup.sh

Add: pip3 install pyfiglet --user

**Comment by Frint0** [comment]
Fixed.
