### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver': 'geckodriver'

### ISSUE THREAD

**Issue by chris9740** [Frint0/email-enum#6]
Got the error "FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver': 'geckodriver'" when executing `sudo python3 check.py email@gmail.com`

Paste: https://hastebin.com/kakoneyeci.sql

Running without `sudo` throws:

https://hastebin.com/ivizuxoyab.sql

**Comment by Frint0** [comment]
```
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.
```

Make sure to run setup.sh before running check.py

**Comment by chris9740** [comment]
I ran it twice, and this is the result of the second time I executed it

https://hastebin.com/qaturoyuyi.rb

**Comment by Frint0** [comment]
Does `~/.local/bin` exist?

**Comment by chris9740** [comment]
Yes, and there is a geckodriver file in it

**Comment by Frint0** [comment]
Is `~/.local/bin/` in your path? Send me the output of `echo $PATH`.

**Comment by chris9740** [comment]
/home/chris/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/pr0n

**Comment by Frint0** [comment]
Hm, the stat error is normal since you already moved it into `~/.local/bin` the first time you ran the script. Although, I'm not sure why `check.py` isn't able to find the geckodriver in your path....

**Comment by Frint0** [comment]
Try running `check.py` again now that geckodriver is in your $PATH.

**Comment by chris9740** [comment]
Thanks for the support, `chmod +x ~/.local/bin/geckodriver` ended up sovling my issue
