### ISSUE TITLE
Message: connection refused

### ISSUE THREAD

**Issue by chris9740** [Frint0/email-enum#7]
Hello,

When running the check.py script, I get the following error:

`selenium.common.exceptions.WebDriverException: Message: connection refused`
(Full error: https://hastebin.com/zenofagaka.sql)

Here is my geckodriver.log https://hastebin.com/olowotucix.sql

**Comment by Frint0** [comment]
Does the directory `home/chris/snap/firefox/common/` exist?

**Comment by chris9740** [comment]
Yes, it does

**Comment by Frint0** [comment]
What version of Firefox are you running?

**Comment by chris9740** [comment]
Mozilla Firefox 65.0.2

**Comment by Frint0** [comment]
Try running `mkdir /home/chris/snap/firefox/common/.config/` and re-running `check.py`.

**Comment by chris9740** [comment]
Still get the same issue

**Comment by Frint0** [comment]
Send geckodriver.log

**Comment by chris9740** [comment]
https://hastebin.com/siyuqisini.sql

**Comment by Frint0** [comment]
Ah, this is an issue with the snap version of Firefox. You can uninstall Firefox via snap and then run `sudo apt install firefox` to fix.
